### ISSUE TITLE
Upgrade to ArcGIS JS API 4.12

### ISSUE THREAD

**Issue by LiamBrandt** [umts/GISMap#88]
- [ ] Make sure everything works
- [ ] ~~Switch to using native promises `Promise` instead of `IPromise` as per the 4.12 release notes~~ (The typescript types package still uses IPromise. I think we will have to wait till 4.14 or 4.15 when they use native by default)

**Comment by LiamBrandt** [comment]
On hold until this is resolved: https://support.esri.com/en/bugs/nimbus/QlVHLTAwMDEyMzc3Mw==

**Comment by LiamBrandt** [comment]
Turns out is was just that this update doesnt work on my computer only, on any browser. So I will have to wait till I have a new computer or fix the problem.

**Comment by Anbranin** [comment]
Do we have an extra computer in the cabinet? If not we can give you one of the ones from up here. We just got a bunch of new laptops.

**Comment by LiamBrandt** [comment]
Waiting for bug 000126233 to be resolved:
https://support.esri.com/en/bugs/nimbus/QlVHLTAwMDEyNjIzMw==
