### ISSUE TITLE
HTTPS redirect

### ISSUE THREAD

**Issue by LiamBrandt** [umts/GISMap#97]
We might want to redirect users to the HTTPS site when they go to the HTTP site like we did on the old map. But it would be useful to have some clause that can tell if it is development or production because there is no such thing as secure through HTTPS localhost. Not sure how possible this is.

**Comment by Anbranin** [comment]
A redirect rule like this would be written on the server, not written in the code. Thus in this case it is not up to us.

**Comment by LiamBrandt** [comment]
Thats a better idea. With the github pages one there probably wasn't a choice.

@UmassGIS would it be possible to redirect from the `http` url to the `https` url in production? That way the find my location will always work?

**Comment by LiamBrandt** [comment]
This appears to have been implemented
